<?php
    $form = $this->commentForm;
    $form->setAttribute(
        'action',
        $this->url('gag', array('slug' => $media->getSlug()))
    );
?>
<section class="col-lg-8 col-md-8 col-sm-8 col-xs-12">
    <!-- #Meme -->
    <article class="meme clearfix" data-slug="<?php echo $media->getSlug() ?>">
        <div class="meme-title">
            <?php echo $media->getName() ?>
        </div>
        <div class="meme-points">
            Points: <span><?php echo $this->media()->getPoints($media) ?></span> &#8226; Comments: <?php echo $this->media()->getComments($media) ?>
        </div>   
        <div class="meme-img">
            <img src="<?php echo $this->media()->url($media, true) ?>" alt="" class="img-responsive" />
        </div>
        <ul class="meme-action clearfix">
            <?php
                    $vote = $this->media()->getVote($media);
                    
                    if(!$this->user()->hasIdentity()):
                ?>
                    <li class="btn-group">
                        <a href="<?php echo $this->url('login') ?>" class="btn btn-default" data-type="up">
                            <span class="glyphicon glyphicon-chevron-up"></span>
                        </a>
                        <a href="<?php echo $this->url('login') ?>" class="btn btn-default" data-type="down">
                            <span class="glyphicon glyphicon-chevron-down"></span>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="btn-group" data-trigger="response">
                        <a href="javascript:void(0);" class="btn btn-default<?php echo $this->media()->isVoteUp($vote) ? ' response-selected' : '' ?>" data-type="up">
                            <span class="glyphicon glyphicon-chevron-up"></span>
                        </a>
                        <a href="javascript:void(0);" class="btn btn-default<?php echo $this->media()->isVoteDown($vote) ? ' response-selected' : '' ?>" data-type="down">
                            <span class="glyphicon glyphicon-chevron-down"></span>
                        </a>
                    </li>
                <?php endif ?>
            <li>
                <a href="#" data-type="facebook" data-url="<?php echo $this->url('gag', array('slug' => $media->getSlug()), array('force_canonical' => true)) ?>" data-description="Click to see the pic and write a comment ..." data-title="<?php echo $media->getName() ?>" data-media="<?php echo $this->media()->url($media) ?>" class="btn btn-facebook">Facebook</a>
            </li>
            <li>
                <a href="#" data-type="twitter" data-url="<?php echo $this->url('gag', array('slug' => $media->getSlug()), array('force_canonical' => true)) ?>" data-description="<?php echo $media->getName() ?>" data-via="GAGchan" data-media="<?php echo $this->media()->url($media) ?>" class="btn btn-twitter">Twitter</a>
            </li>
            <li>
                <a data-clipboard-text="<?php echo $this->url('gag', array('slug' => $media->getSlug()), array('force_canonical' => true)) ?>"  class="btn btn-default zeroclipboard">
                    <span class="glyphicon glyphicon-link"></span>
                </a>
            </li>
        </ul>
    </article>

    <!-- #Comments -->
    <article class="comments">
        <h3 class="comments-title">Comments</h3>
        
        <?php if ($this->user()->hasIdentity()): ?>
        
            <div class="widget">
                
                <?php echo $this->form()->openTag($form) ?>

                    <div class="form-row">
                        <?php echo $this->formTextarea($form->get('comment')) ?>

                        <?php echo $this->formElementErrors($form->get('comment')) ?>
                    </div>

                    <?php echo $this->formButton($form->get('submit')) ?>

                <?php echo $this->form()->closeTag() ?>
            
            </div>
        
        <?php else: ?>
        
            <div class="widget">
                
                <div class="form-row">
                    You have to be logged in to post a comment.
                </div>
                
                <a href="<?php echo $this->url('login') ?>" class="btn btn-primary">Log in</a>

            </div>
        
        <?php endif ?>
        
        <hr />
        
        <?php foreach($this->comments as $comment): ?>
            <div class="comment-widget">
                <div class="user-details">
                    <?php echo $this->user()->findById($comment->getUserId())->getUsername() ?> <small>(<?php echo $this->comment()->dateDiff($comment->getCreatedAt()) ?>)</small>
                </div>
                <div class="comment-text">
                    <?php echo $comment->getComment() ?>
                </div>
            </div>
        <?php endforeach ?>
    </article>
</section>

<!-- #Sidebar -->
<section id="sidebar" class="col-lg-4 col-md-4 col-sm-4 hidden-xs">
    <div class="widget meme-listing">
        <h3 class="widget-title">Featured</h3>

        <?php $featured = $this->media()->getFeatured() ?>
        
        <?php if (count($featured) === 0): ?>
            There is no media right now.
        <?php endif ?>
        
        <?php foreach ($featured as $f): ?>
        
        <article class="meme">
            <a href="<?php echo $this->url('gag', array('slug' => $f->getSlug())) ?>" class="meme-img">
                <img src="<?php echo $this->media()->url($f) ?>" alt="" class="img-responsive" />
            </a>
            <div class="meme-title">
                <a href="<?php echo $this->url('gag', array('slug' => $f->getSlug())) ?>">
                    <?php echo $f->getName() ?>
                </a>
            </div>
        </article>
        
        <?php endforeach ?>
        
    </div>

    <div class="widget">
        <h3 class="widget-title">Share with your friends</h3>
        
        <ul class="social-share clearfix">
            <li>
                <div class="fb-like" data-href="https://www.facebook.com/pages/GAGchan/905727472786344" data-width="100" data-layout="box_count" data-action="like" data-show-faces="false" data-share="false"></div>
            </li>
            <li>
                <div class="g-plusone" data-size="tall"></div>
            </li>
        </ul>
    </div>
    
    <ul class="quicknav clearfix">
        <li><a href="<?php echo $this->url('privacy') ?>">Privacy policy</a></li>
        <li>&#8226;</li>
        <li><a href="<?php echo $this->url('terms') ?>">Terms of use</a></li>
        <li>&#8226;</li>
        <li><a href="<?php echo $this->url('contact') ?>">Contact</a></li>
    </ul>
</section>
