<section class="col-lg-8 col-md-8 col-sm-8 col-xs-12 meme-listing">
    
    <?php if (count($media) === 0): ?>
        There is no media right now.
    <?php endif ?>
    
    <?php foreach ($media as $m): ?>
        
        <article class="meme clearfix" data-slug="<?php echo $m->getSlug() ?>">
            <div class="meme-title">
                <a href="<?php echo $this->url('gag', array('slug' => $m->getSlug())) ?>">
                    <?php echo $m->getName() ?>
                </a>
            </div>
            <div class="meme-points">
                Points: <span><?php echo $this->media()->getPoints($m) ?></span> &#8226; Comments: <?php echo $this->media()->getComments($m) ?>
            </div>
            <a href="<?php echo $this->url('gag', array('slug' => $m->getSlug())) ?>" class="meme-img">
                <img src="<?php echo $this->media()->url($m, true) ?>" alt="" class="img-responsive" />
            </a>
            <ul class="meme-action clearfix">
                <?php
                    $vote = $this->media()->getVote($m);
                    
                    if(!$this->user()->hasIdentity()):
                ?>
                    <li class="btn-group">
                        <a href="<?php echo $this->url('login') ?>" class="btn btn-default" data-type="up">
                            <span class="glyphicon glyphicon-chevron-up"></span>
                        </a>
                        <a href="<?php echo $this->url('login') ?>" class="btn btn-default" data-type="down">
                            <span class="glyphicon glyphicon-chevron-down"></span>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="btn-group" data-trigger="response">
                        <a href="javascript:void(0);" class="btn btn-default<?php echo $this->media()->isVoteUp($vote) ? ' response-selected' : '' ?>" data-type="up">
                            <span class="glyphicon glyphicon-chevron-up"></span>
                        </a>
                        <a href="javascript:void(0);" class="btn btn-default<?php echo $this->media()->isVoteDown($vote) ? ' response-selected' : '' ?>" data-type="down">
                            <span class="glyphicon glyphicon-chevron-down"></span>
                        </a>
                    </li>
                <?php endif ?>
                <li>
                    <a href="#" data-type="facebook" data-url="<?php echo $this->basePath() . $this->url('gag', array('slug' => $m->getSlug())) ?>" data-description="Click to see the pic and write a comment ..." data-title="<?php echo $m->getName() ?>" data-media="<?php echo $this->media()->url($m) ?>" class="btn btn-facebook">Facebook</a>
                </li>
                <li>
                    <a href="#" data-type="twitter" data-url="<?php echo $this->basePath() . $this->url('gag', array('slug' => $m->getSlug())) ?>" data-description="<?php echo $m->getName() ?>" data-via="GAGchan" data-media="<?php echo $this->media()->url($m) ?>" class="btn btn-twitter">Twitter</a>
                </li>
                <li>
                    <a data-clipboard-text="<?php echo $this->basePath() . $this->url('gag', array('slug' => $m->getSlug())) ?>"  class="btn btn-default zeroclipboard">
                        <span class="glyphicon glyphicon-link"></span>
                    </a>
                </li>
            </ul>
        </article>
    
    <?php endforeach ?>
    
    <?php echo $this->paginationControl($media, 'sliding', array('partial/paginator.phtml', 'Media'), array('route' => 'home')) ?>
    
</section>

<section id="sidebar" class="col-lg-4 col-md-4 col-sm-4 hidden-xs">    
    <div class="widget meme-listing">
        <h3 class="widget-title">Featured</h3>
        
        <?php $featured = $this->media()->getFeatured() ?>
        
        <?php if (count($featured) === 0): ?>
            There is no media right now.
        <?php endif ?>
        
        <?php foreach ($featured as $f): ?>
        
        <article class="meme">
            <a href="<?php echo $this->url('gag', array('slug' => $f->getSlug())) ?>" class="meme-img">
                <img src="<?php echo $this->media()->url($f, true) ?>" alt="" class="img-responsive" />
            </a>
            <div class="meme-title">
                <a href="<?php echo $this->url('gag', array('slug' => $f->getSlug())) ?>">
                    <?php echo $f->getName() ?>
                </a>
            </div>
        </article>
        
        <?php endforeach ?>
        
    </div>
    
    <div class="widget">
        <h3 class="widget-title">Share with your friends</h3>
        
        <ul class="social-share clearfix">
            <li>
                <div class="fb-like" data-href="https://www.facebook.com/pages/GAGchan/905727472786344" data-width="100" data-layout="box_count" data-action="like" data-show-faces="false" data-share="false"></div>
            </li>
            <li>
                <div class="g-plusone" data-size="tall"></div>
            </li>
        </ul>
    </div>
</section>
