<?php
    $mediaForm = $this->mediaForm;
?>

<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

    <div class="widget">
        <?php echo $this->form()->openTag($mediaForm) ?>
            
            <h3 class="login-title">Upload from computer ...</h3>

            <!-- #Name -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-tag"></span>
                    </span>
                    <?php echo $this->formInput($mediaForm->get('name')) ?>
                </div>

                <?php echo $this->formElementErrors($mediaForm->get('name')) ?>
            </div>
            
            <!-- #File -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-file"></span>
                    </span>
                    <?php echo $this->formFile($mediaForm->get('file')) ?>
                </div>

                <?php echo $this->formElementErrors($mediaForm->get('file')) ?>
            </div>
            
            <!-- #Category -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-flag"></span>
                    </span> 
                    <?php echo $this->formSelect($mediaForm->get('category')) ?>
                </div>

                <?php echo $this->formElementErrors($mediaForm->get('category')) ?>
            </div>
            
            <div class="input-group">
                <?php echo $this->formButton($mediaForm->get('submit')) ?>
            </div>
            
        <?php echo $this->form()->closeTag() ?>
    </div>

</section>

<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

    <div class="widget">
        <?php echo $this->form()->openTag($mediaForm) ?>

            <h3 class="login-title">Or copy from URL ...</h3>

            <!-- #Name -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-tag"></span>
                    </span>
                    <?php echo $this->formInput($mediaForm->get('name')) ?>
                </div>

                <?php echo $this->formElementErrors($mediaForm->get('name')) ?>
            </div>

            <!-- #URL -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-file"></span>
                    </span>
                    <?php echo $this->formInput($mediaForm->get('url')) ?>
                </div>

                <?php echo $this->formElementErrors($mediaForm->get('url')) ?>
            </div>
            
            <!-- #Category -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-flag"></span>
                    </span>
                    <?php echo $this->formSelect($mediaForm->get('category')) ?>
                </div>

                <?php echo $this->formElementErrors($mediaForm->get('category')) ?>
            </div>

            <div class="input-group">
                <?php echo $this->formButton($mediaForm->get('submit')) ?>
            </div>
            
        <?php echo $this->form()->closeTag() ?>
    </div>

</section>