<?php
    $form = $this->loginForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/login'));
    $form->setAttribute('method', 'post');
    
    $form->get('identity')
        ->setAttribute('class', 'form-control')
        ->setAttribute('placeholder', $form->get('identity')->getLabel())
    ;
    
    $form->get('credential')
        ->setAttribute('class', 'form-control')
        ->setAttribute('placeholder', $form->get('credential')->getLabel())
    ;
    
    $form->get('submit')
        ->setAttribute('class', 'btn btn-primary')
    ;
?>

<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
    
    <div class="widget">
        <h3 class="login-title">Login</h3>
        
        <?php echo $this->form()->openTag($form) ?>
            
            <!-- #Email -->
            <div class="form-row input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-envelope"></span>
                </span>
                <?php echo $this->formInput($form->get('identity')) ?>
                <!-- <input type="text" class="form-control" placeholder="Email"> -->
            </div>

            <?php echo $this->formElementErrors($form->get('identity')) ?>
        
            <!-- #Password -->
            <div class="form-row input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-lock"></span>
                </span>
                <?php echo $this->formInput($form->get('credential')) ?>
            </div>

            <?php if ($this->redirect): ?>
                <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
            <?php endif ?>
            
            <div class="input-group">
                <?php echo $this->formButton($form->get('submit')) ?>
            </div>
            
        <?php echo $this->form()->closeTag() ?>
    </div>

    <div class="widget">
        <div class="login-title">
            <h3 class="login-title">Or login with ...</h3>
        </div>

        <div class="hidden-overflow">
            <ul class="btn-social-group clearfix">
                <li>
                    <a href="<?php echo $this->url('scn-social-auth-user/login/provider', array('provider' => 'facebook')) ?>" class="btn btn-facebook">Facebook</a>
                </li>

                <li>
                    <a href="<?php echo $this->url('scn-social-auth-user/login/provider', array('provider' => 'google')) ?>" class="btn btn-google">Google</a>
                </li>
            </ul>
        </div>
    </div>

</section>

<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">          

    <div class="widget">
        <h3 class="login-title">No account yet?</h3>

        <div style="padding: 20px; background: #e8e8e8; border-radius: 4px; text-align: center;">
            Join us now for free!
            <div style="margin-top: 20px;">
             <a href="<?php echo $this->url('zfcuser/register') ?>" class="btn btn-primary">Sign up</a>
            </div>
        </div>
    </div>

</section>
