<?php
    $form = $this->registerForm;
    $form->prepare();
    $form->setAttribute('action', $this->url('zfcuser/register'));
    $form->setAttribute('method', 'post');
    
    $form->get('username')
        ->setAttribute('class', 'form-control')
        ->setAttribute('placeholder', $form->get('username')->getLabel())
    ;
    
    $form->get('email')
        ->setAttribute('class', 'form-control')
        ->setAttribute('placeholder', $form->get('email')->getLabel())
    ;
    
    $form->get('password')
        ->setAttribute('class', 'form-control')
        ->setAttribute('placeholder', $form->get('password')->getLabel())
    ;
    
    $form->get('passwordVerify')
        ->setAttribute('class', 'form-control')
        ->setAttribute('placeholder', $form->get('passwordVerify')->getLabel())
    ;
    
    $form->get('submit')
        ->setAttribute('class', 'btn btn-primary')
    ;
?>

<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

    <div class="widget">
        <h3 class="login-title">Sign up</h3>
        
        <?php echo $this->form()->openTag($form) ?>
        
            <!-- #Username -->
            <div class="form-row input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-user"></span>
                </span>
                <?php echo $this->formInput($form->get('username')) ?>
            </div>

            <?php echo $this->formElementErrors($form->get('username')) ?>
            
            <!-- #Email -->
            <div class="form-row input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-envelope"></span>
                </span>
                <?php echo $this->formInput($form->get('email')) ?>
            </div>

            <?php echo $this->formElementErrors($form->get('email')) ?>
            
            <!-- #Password -->
            <div class="form-row input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-lock"></span>
                </span>
                <?php echo $this->formInput($form->get('password')) ?>
            </div>

            <?php echo $this->formElementErrors($form->get('password')) ?>
            
            <div class="form-row input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-lock"></span>
                </span>
                <?php echo $this->formInput($form->get('passwordVerify')) ?>
            </div>
            
            <?php echo $this->formElementErrors($form->get('passwordVerify')) ?>
            
            <?php if ($this->redirect): ?>
                <input type="hidden" name="redirect" value="<?php echo $this->escapeHtml($this->redirect) ?>" />
            <?php endif ?>
                
            <div class="input-group">
                <?php echo $this->formButton($form->get('submit')) ?>
            </div>
            
        <?php echo $this->form()->closeTag() ?>
    </div>

    <div class="widget">
        <div class="login-title">
            <h3 class="login-title">Or sign up with ...</h3>
        </div>

        <div class="hidden-overflow">
            <ul class="btn-social-group clearfix">
                <li>
                    <a href="<?php echo $this->url('scn-social-auth-user/login/provider', array('provider' => 'facebook')) ?>" class="btn btn-facebook">Facebook</a>
                </li>

                <li>
                    <a href="#" class="btn btn-twitter">Twitter</a>
                </li>
            </ul>
        </div>
    </div>

</section>

<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">          

    <div class="widget">
        <h3 class="login-title">Already have an account?</h3>

        <div style="padding: 20px; background: #e8e8e8; border-radius: 4px; text-align: center;">
            Log in now and upload your meme for free!
            <div style="margin-top: 20px;">
             <a href="<?php echo $this->url('zfcuser/login') ?>" class="btn btn-primary">Log in</a>
            </div>
        </div>
    </div>

</section>