<?php $this->headTitle()->append('Account settings') ?>

<section class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
    
    <?php echo $this->navigation('user.navigation')->menu()->renderMenu(null, array('ulClass' => 'sidenav')) ?>
    
</section>

<section class="col-lg-8 col-md-8 col-sm-8 col-xs-8">

    <?php foreach ($messages as $m): ?>
        <div class="alert alert-success" role="alert"><?php echo $m ?></div>
    <?php endforeach ?>

    <div class="widget">
        <h3 class="widget-title">Account settings</h3>
        
        <?php echo $this->form()->openTag($settingsForm) ?>
        
            <!-- #CSRF -->
            <?php echo $this->formHidden($settingsForm->get('csrf')) ?>
        
            <!-- #Username -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-user"></span>
                    </span>
                    <?php echo $this->formInput($settingsForm->get('username')) ?>
                </div>

                <?php echo $this->formElementErrors($settingsForm->get('username')) ?>
            </div>
            
            <!-- #Email -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-envelope"></span>
                    </span>
                    <?php echo $this->formInput($settingsForm->get('email')) ?>
                </div>

                <?php echo $this->formElementErrors($settingsForm->get('email')) ?>
            </div>

            <div class="input-group">
                <?php echo $this->formButton($settingsForm->get('submit')) ?>
            </div>
            
        <?php echo $this->form()->closeTag() ?>
    </div>

</section>
