<section class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
    
    <ul class="sidenav">
        <li>
            <a href="<?php echo $this->url('settings') ?>">Account</a>
        </li>
        <li>
            <a href="<?php echo $this->url('settings/password') ?>">Password</a>
        </li>
    </ul>
    
</section>

<section class="col-lg-8 col-md-8 col-sm-8 col-xs-8">
    
    <?php foreach ($messages as $m): ?>
        <div class="alert alert-success" role="alert"><?php echo $m ?></div>
    <?php endforeach ?>

    <div class="widget">
        <h3 class="login-title">Password settings</h3>
        
        <?php echo $this->form()->openTag($settingsForm) ?>
        
            <!-- #CSRF -->
            <?php echo $this->formHidden($settingsForm->get('csrf')) ?>
        
            <!-- #Password -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-lock"></span>
                    </span>
                    <?php echo $this->formInput($settingsForm->get('password')) ?>
                </div>

                <?php echo $this->formElementErrors($settingsForm->get('password')) ?>
            </div>
            
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-lock"></span>
                    </span>
                    <?php echo $this->formInput($settingsForm->get('password_verify')) ?>
                </div>

                <?php echo $this->formElementErrors($settingsForm->get('password_verify')) ?>
            </div>

            <div class="input-group">
                <?php echo $this->formButton($settingsForm->get('submit')) ?>
            </div>
            
        <?php echo $this->form()->closeTag() ?>
    </div>

</section>
