<?php $this->headTitle()->append('Social Networks') ?>

<section class="col-lg-4 col-md-4 col-sm-4 col-xs-4">
    
    <ul class="sidenav">
        <li>
            <a href="<?php echo $this->url('settings') ?>">Account</a>
        </li>
        <li>
            <a href="<?php echo $this->url('settings/password') ?>">Password</a>
        </li>
        <li>
            <a href="<?php echo $this->url('settings/social') ?>">Social Networks</a>
        </li>
    </ul>
    
</section>

<section class="col-lg-8 col-md-8 col-sm-8 col-xs-8">

    <?php foreach ($messages as $m): ?>
        <div class="alert alert-success" role="alert"><?php echo $m ?></div>
    <?php endforeach ?>

    <div class="widget">
        <h3 class="widget-title">Facebook</h3>
        
        <?php if (empty($isFacebook)): ?>
            Not connected &#8226; <a href="<?php echo $this->url('connect', array('provider' => 'facebook')) ?>">Connect</a><br />
            <br />
            <div class="alert alert-info" role="alert">
                You might need to confirm that you agree that we gather some of
                your basic information from your social, otherwise we are unable
                to confirm your identity.<br />
            </div>
        <?php else: ?>
            You are connected &#8226; <a href="<?php echo $this->url('disconnect', array('provider' => 'facebook')) ?>">Disconnect</a><br />
            <br />
            <div class="alert alert-info" role="alert">
                If you disconnect your account from social network you might
                not be able to log in again, or you might not be able to use
                some of our services.<br />
            </div>
        <?php endif ?>
    </div>

    <div class="widget">
        <h3 class="widget-title">Google</h3>
        
        <?php if (empty($isGoogle)): ?>
            Not connected &#8226; <a href="<?php echo $this->url('connect', array('provider' => 'google')) ?>">Connect</a><br />
            <br />
            <div class="alert alert-info" role="alert">
                You might need to confirm that you agree that we gather some of
                your basic information from your social, otherwise we are unable
                to confirm your identity.<br />
            </div>
        <?php else: ?>
            You are connected &#8226; <a href="<?php echo $this->url('disconnect', array('provider' => 'google')) ?>">Disconnect</a><br />
            <br />
            <div class="alert alert-info" role="alert">
                If you disconnect your account from social network you might
                not be able to log in again, or you might not be able to use
                some of our services.<br />
            </div>
        <?php endif ?>
    </div>
</section>
