<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('GAGchan')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendName('description', 'GAGchan is your best source of happiness and awesomeness online!')
        ->appendName('keywords', 'meme, fun, gagchan, gag, happy, happiness, awesome, gif, funny pic, girl, comic, WTF, cute, geeky')
    ?>

    <!-- Favicon -->
    <?php echo $this->headLink(array('rel'  => 'shortcut icon', 'type' => 'image/png', 'href' => '/images/favicon.png')) ?>

    <!-- Styles -->
    <?php echo $this->headLink()
        ->prependStylesheet('/css/layout.css')
        ->prependStylesheet('/css/bootstrap.min.css')
    ?>

    <!-- Google Fonts -->
    <?php echo $this->headLink()
        ->prependStylesheet('http://fonts.googleapis.com/css?family=Roboto+Slab:400,700&subset=latin,latin-ext')
        ->prependStylesheet('http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic&subset=latin,latin-ext')
    ?>
    
    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile('/js/bootstrap.min.js')
        ->prependFile('/js/jquery.prettySocial.min.js')
        ->prependFile('/js/jquery.zeroclipboard.min.js')
        ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js', 'text/javascript')
        ->prependFile('https://oss.maxcdn.com/respond/1.4.2/respond.min.js',   'text/javascript', array('conditional' => 'lt IE 9'))
        ->prependFile('https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
    ?>
    
    <script>
        jQuery(document).ready(function($) {
            // Share on social networks
            $(".btn-facebook, .btn-twitter").prettySocial();

            // Google Plus One
            (function() {
                var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
                po.src = 'https://apis.google.com/js/platform.js';
                var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
            })();

            // FB like box
            (function(d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = "//connect.facebook.net/sl_SI/sdk.js#xfbml=1&appId=782048061815836&version=v2.0";
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));

            // Copy to clipboard
            new ZeroClipboard($('.zeroclipboard'), {
                moviePath : 'js/jquery.zeroclipboard.swf'
            });

            // Vote 
            $('[data-trigger="response"] > a').click(function(e) {
                // Element parameters
                var $this = $(this);
                var $type = $this.data('type');

                // Check if item is not selected
                if (!$this.hasClass('response-selected')) {
                    // Article parameters
                    var $article = $this.parents('.meme');
                    var $slug    = $article.data('slug');

                    // Ajax request
                    $.ajax({
                        data: { slug: $slug, type: $type },
                        type: 'POST',
                        url:  '<?php echo $this->url('vote') ?>'
                    }).done(function(data) { 
                        // Check if action was successful
                        if (data.result === true) {
                            // Parent parameters
                            var $parent = $this.parent();

                            // Change points
                            $article.find('.meme-points > span').html(data.points);

                            // Remove class from others
                            $parent.find('a').removeClass('response-selected');

                            // Add class
                            $this.addClass('response-selected');
                        }
                    });
                }

                // Prevent default action
                e.preventDefault();
            });

            $('.zeroclipboard').click(function() {
                // Current element
                var $this = $(this);

                // Remove selected class from others
                $('.zeroclipboard').removeClass('zeroclipboard-selected');

                // Add class to current element
                $this.addClass('zeroclipboard-selected');
            });

            // GIF play on click
            $('a.meme-img').has('.play').click(function(){
                var $this = $(this);
                var $img  = $this.find('img');

                if (!this.playing) {
                    // Change source to GIF
                    $img.attr('src', $img.attr('src').replace('s_v1.jpg', 'sa_v1.gif'));

                    // Hide span 
                    $this.find('.play').hide();
                    this.playing = true;
                }
                else {
                    // Change source to static image                
                    $img.attr('src', $img.attr('src').replace('sa_v1.gif', 's_v1.jpg'));

                    // Show span
                    $this.find('.play').show();
                    this.playing = false;
                }

                return false;
            });

            // Meme generator preview
            var img = $('#preview');
            var src = img.attr('src');
            
            $('[name=top]').focusout(function(){
                if($.trim($(this).val()) != "") {                      
                    SendAjaxRequest($('[name=top]').val(), $(this).val(), src, 'topText');
                }
            });

            $('[name=bottom]').focusout(function(){
                if($.trim($(this).val()) != "") {
                    SendAjaxRequest($(this).val(), $('[name=bottom]').val(), src, 'bottomText');
                }
            });

            function SendAjaxRequest(umsg, dmsg, src, type)
            { 
                $.ajax({
                    url: '<?php echo $this->url('preview') ?>',
                    type: 'POST',
                    data: { 
                        upmsg : umsg, 
                        downmsg : dmsg, 
                        imgsrc: src,
                        position: type 
                    },                         
                    success: function(response) {
                       $('#preview').attr('src', response.name);
                      // img.attr('src', img.attr('src').replace(src, e));

                    },
                    error: function(response) {
                        alert("napaka");
                    }
                }); 
                
                // Prevent default action
               // e.preventDefault();
            }  
        });
             
    </script>
</head>
<body>
    <!-- #Navigation Bar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        
        <div class="container">
            
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('home') ?>"></a>
            </div><!--/.navbar-header -->
            
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="<?php echo $this->url('home') ?>">Latest</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Browse by category <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <?php foreach ($this->category()->getCategories() as $category): ?>
                                <li>
                                    <a href="<?php echo $this->url('category', array('slug' => $category->getSlug())) ?>"><?php echo $category->getName() ?></a>
                                </li>
                            <?php endforeach ?>
                        </ul>
                    </li>
                </ul>
                
                <ul class="nav navbar-nav navbar-right">
                    <?php if(!$this->user()->hasIdentity()): ?>
                        <li>
                            <a href="<?php echo $this->url('login') ?>">Log in</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('signup') ?>">Sign up</a>
                        </li>
                    <?php else: ?>
                        <li class="dropdown">
                            <a href="#"  class="dropdown-toggle" data-toggle="dropdown">
                                <?php echo $this->user()->getIdentity()->getUsername(); ?> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="<?php echo $this->url('settings') ?>">Settings</a></li>
                                <li><a href="<?php echo $this->url('logout') ?>">Logout</a></li>
                            </ul>
                        </li>
                    <?php endif ?>
                    <li class="dropdown">
                        <a class="dropdown-toggle strong" data-toggle="dropdown" href="<?php echo $this->url('upload') ?>">Upload</a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="<?php echo $this->url('upload') ?>">From computer</a></li>
                                <li><a href="<?php echo $this->url('upload/external') ?>">From URL</a></li>
                                <li><a href="<?php echo $this->url('generator') ?>">Generate your own</a></li>
                            </ul>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
            
        </div>
        
    </div><!--/.navbar -->

    <!-- #Content -->
    <div id="content" class="container clearfix">
        
        <?php echo $this->content; ?>
        
    </div><!-- /.container -->
    
    <?php echo $this->inlineScript() ?>
</body>
</html>
