<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('GAGchan')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendName('description', 'GAGchan is your best source of happiness and awesomeness online!')
        ->appendName('keywords', 'meme, fun, gagchan, gag, happy, happiness, awesome, gif, funny pic, girl, comic, WTF, cute, geeky')
    ?>

    <!-- Favicon -->
    <?php echo $this->headLink(array('rel'  => 'shortcut icon', 'type' => 'image/png', 'href' => '/images/favicon.png')) ?>

    <!-- Styles -->
    <?php echo $this->headLink()
        ->prependStylesheet('/css/layout.css')
        ->prependStylesheet('/css/bootstrap.min.css')
    ?>

    <!-- Google Fonts -->
    <?php echo $this->headLink()
        ->prependStylesheet('//fonts.googleapis.com/css?family=Roboto+Slab:400,700&subset=latin,latin-ext')
        ->prependStylesheet('//fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic&subset=latin,latin-ext')
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile('//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js', 'text/javascript')
        ->prependFile('//oss.maxcdn.com/respond/1.4.2/respond.min.js',   'text/javascript', array('conditional' => 'lt IE 9'))
        ->prependFile('//oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
    ?>
</head>
<body>
    <!-- #Navigation Bar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">

        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<?php echo $this->url('home') ?>"></a>
            </div><!--/.navbar-header -->

            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="<?php echo $this->url('home') ?>">Latest</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Browse by category <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <?php foreach ($this->category()->getCategories() as $category): ?>
                                <li>
                                    <a href="<?php echo $this->url('category', array('slug' => $category->getSlug())) ?>"><?php echo $category->getName() ?></a>
                                </li>
                            <?php endforeach ?>
                        </ul>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    <?php if(!$this->user()->hasIdentity()): ?>
                        <li>
                            <a href="<?php echo $this->url('login') ?>">Log in</a>
                        </li>
                        <li>
                            <a href="<?php echo $this->url('signup') ?>">Sign up</a>
                        </li>
                    <?php else: ?>
                        <li class="dropdown">
                            <a href="#"  class="dropdown-toggle" data-toggle="dropdown">
                                <?php echo $this->user()->getIdentity()->getUsername(); ?> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="<?php echo $this->url('settings') ?>">Settings</a></li>
                                <li><a href="<?php echo $this->url('logout') ?>">Logout</a></li>
                            </ul>
                        </li>
                    <?php endif ?>
                    <li class="dropdown">
                        <a class="dropdown-toggle strong" data-toggle="dropdown" href="<?php echo $this->url('upload') ?>">Upload</a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="<?php echo $this->url('upload') ?>">From computer</a></li>
                                <li><a href="<?php echo $this->url('upload/external') ?>">From URL</a></li>
                                <li><a href="<?php echo $this->url('generator') ?>">Create your own</a></li>
                            </ul>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->

        </div>

    </div><!--/.navbar -->

    <!-- #Content -->
    <div id="content" class="container clearfix">

        <?php echo $this->content; ?>

    </div><!-- /.container -->

    <?php echo $this->inlineScript()
        ->prependFile('/js/bootstrap.min.js')
        ->prependFile('/js/jquery.gagchan.js')
        ->prependFile('/js/jquery.prettySocial.min.js')
        ->prependFile('/js/jquery.zeroclipboard.min.js')
    ?>

    <script>
        // Google Plus One
        (function() {
            var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
            po.src = '//apis.google.com/js/platform.js';
            var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
        })();

        // Facebook Like
        (function(d, s, id) {
            var js, fjs = d.getElementsByTagName(s)[0];
            if (d.getElementById(id)) return;
            js = d.createElement(s); js.id = id;
            js.src = "//connect.facebook.net/sl_SI/sdk.js#xfbml=1&appId=782048061815836&version=v2.0";
            fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
</body>
</html>
