Hello <?php echo $user->getUsername() ?>!<br />
<br />
You have requested a password recovery. You can recover your password by visiting the following URL:<br />
<?php echo $url ?><br />
<br />
You have to recover your password within one week, otherwise the recovery request will expire.<br />
<br />
This request was made from the following host: <?php echo $host ?><br />
<br />
Kind regards,<br />
GAGchan<br />
