<?php
    $form = $this->form;
    $form->prepare();
?>

<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
    
    <div class="widget">
        <?php echo $this->form()->openTag($form) ?>
        
        <h3 class="login-title">Contact us</h3>
        
            <!-- #From -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-user"></span>
                    </span>
                    <?php echo $this->formInput($form->get('from')) ?>
                </div>

                <?php echo $this->formElementErrors($form->get('from')) ?>
            </div>      
            
            <!-- #Subject -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-envelope"></span>
                    </span>
                    <?php echo $this->formInput($form->get('subject')) ?>
                </div>

                <?php echo $this->formElementErrors($form->get('subject')) ?>
            </div>            
            
            <!-- #Body -->
            <div class="form-row">

                <?php echo $this->formTextarea($form->get('body')) ?>
                <?php echo $this->formElementErrors($form->get('body')) ?>
                
            </div>         
            
            <div class="input-group">
                <?php 
                echo $this->formElement($form->get('csrf'));
                echo $this->formSubmit($form->get('Send'));
                echo $this->formElementErrors($form->get('Send'));
                ?>
            </div>
            
        <?php echo $this->form()->closeTag() ?>            
    </div>

</section>

<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">          

    <div class="widget">
        <h3 class="login-title">Have a question for us?</h3>

        <div class="contact-desc">
            Fill the form on the left side and send us your question!
            <br><br>
            We will try to answer you as soon as possible!
        </div>
    </div>

</section>