<?php $this->headTitle()->append('Log in') ?>

<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

    <div class="widget">
        <h3 class="widget-title">Log in</h3>

        <?php foreach($messages as $m): ?>
            <div class="alert alert-danger"><?php echo $m ?></div>
        <?php endforeach ?>

        <?php echo $this->form()->openTag($loginForm) ?>

            <!-- #CSRF -->
            <?php echo $this->formHidden($loginForm->get('csrf')) ?>

            <!-- #Email -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-envelope"></span>
                    </span>
                    <?php echo $this->formInput($loginForm->get('email')) ?>
                </div>

                <?php echo $this->formElementErrors($loginForm->get('email')) ?>
            </div>

            <!-- #Password -->
            <div class="form-row">
                <div class="form-row input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-lock"></span>
                    </span>
                    <?php echo $this->formInput($loginForm->get('password')) ?>
                    <a href="<?php echo $this->url('recover') ?>" class="input-group-addon btn btn-default">
                        Forgot password
                    </a>
                </div>

                <?php echo $this->formElementErrors($loginForm->get('password')) ?>
            </div>

            <!-- #Submit -->
            <div class="input-group">
                <?php echo $this->formSubmit($loginForm->get('submit')) ?>
            </div>

        <?php echo $this->form()->closeTag() ?>
    </div>

    <div class="widget">
        <h3 class="widget-title">Or log in with ...</h3>

        <div class="hidden-overflow">
            <ul class="btn-social-group clearfix">
                <li>
                    <a href="<?php echo $this->url('oauth', array('provider' => 'Facebook')) ?>" class="btn btn-facebook">Facebook</a>
                </li>

                <li>
                    <a href="<?php echo $this->url('oauth', array('provider' => 'Google')) ?>" class="btn btn-google">Google</a>
                </li>
            </ul>
        </div>
    </div>

</section>

<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

    <div class="widget">
        <h3 class="widget-title">No account yet?</h3>

        <div class="widget-content">
            Join us now for free!<br />
            <br />
            <a href="<?php echo $this->url('signup') ?>" class="btn btn-primary">Sign up</a>
        </div>
    </div>

</section>
