<?php $this->headTitle()->append('Sign up') ?>

<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

    <div class="widget">
        <h3 class="widget-title">Sign up</h3>

        <?php echo $this->form()->openTag($signupForm) ?>

            <!-- #CSRF -->
            <?php echo $this->formHidden($signupForm->get('csrf')) ?>

            <!-- #Username -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-user"></span>
                    </span>
                    <?php echo $this->formInput($signupForm->get('username')) ?>
                </div>

                <?php echo $this->formElementErrors($signupForm->get('username')) ?>
            </div>

            <!-- #Email -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-envelope"></span>
                    </span>
                    <?php echo $this->formInput($signupForm->get('email')) ?>
                </div>

                <?php echo $this->formElementErrors($signupForm->get('email')) ?>
            </div>

            <!-- #Password -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-lock"></span>
                    </span>
                    <?php echo $this->formInput($signupForm->get('password')) ?>
                </div>

                <?php echo $this->formElementErrors($signupForm->get('password')) ?>
            </div>

            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-lock"></span>
                    </span>
                    <?php echo $this->formInput($signupForm->get('password_verify')) ?>
                </div>

                <?php echo $this->formElementErrors($signupForm->get('password_verify')) ?>
            </div>

            <!-- #Captcha -->
            <div class="form-row">
                <?php echo $this->formCaptcha($signupForm->get('captcha')) ?>

                <?php echo $this->formElementErrors($signupForm->get('captcha')) ?>
            </div>

            <div class="input-group">
                <?php echo $this->formButton($signupForm->get('submit')) ?>
            </div>

        <?php echo $this->form()->closeTag() ?>
    </div>

    <div class="widget">
        <h3 class="widget-title">Or sign up with ...</h3>

        <div class="hidden-overflow">
            <ul class="btn-social-group clearfix">
                <li>
                    <a href="<?php echo $this->url('oauth', array('provider' => 'Facebook')) ?>" class="btn btn-facebook">Facebook</a>
                </li>

                <li>
                    <a href="<?php echo $this->url('oauth', array('provider' => 'Google')) ?>" class="btn btn-google">Google</a>
                </li>
            </ul>
        </div>
    </div>

</section>

<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

    <div class="widget">
        <h3 class="widget-title">Already have an account?</h3>

        <div class="widget-content">
            Log in now and upload your meme for free!<br />
            <br />
            <a href="<?php echo $this->url('login') ?>" class="btn btn-primary">Log in</a>
        </div>
    </div>

</section>