<section class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    
    <div class="widget">
        <h3 class="login-title">Sign up</h3>
        You have successfully signed up. You must confirm your email address, before you can log in to your new account.<br />
        <br />
        An email message with confirmation token has been sent to your email address.<br />
    </div>

</section>
