<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
    
    <div class="widget">
        <?php echo $this->form()->openTag($form) ?>
            <h3 class="widget-title"><?php echo $generator->getName(); ?></h3>

            <div class="meme clearfix">
                <img src="<?php echo $this->generator()->url($generator, true) ?>" alt="" class="img-responsive" />
            </div>
        
            <!-- #Upper text -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-arrow-up"></span>
                    </span>
                    <?php echo $this->formInput($form->get('top')) ?>
                </div>
                
                <?php echo $this->formElementErrors($form->get('top')) ?>
            </div>      
            
            <!-- #Bottom text -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-arrow-down"></span>
                    </span>
                    <?php echo $this->formInput($form->get('bottom')) ?>
                </div>
                
                <?php echo $this->formElementErrors($form->get('bottom')) ?>
            </div> 
            
            <div class="input-group">
                <?php echo $this->formButton($form->get('download')) ?>
                <?php echo $this->formButton($form->get('publish')) ?>
            </div>
        <?php echo $this->form()->closeTag() ?>        
            
        <div id="error"></div>
    </div>

</section>

<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">          

    <div class="widget">
        <h3 class="widget-title">Preview your meme</h3>

        <div class="meme clearfix">
            <img src="<?php echo $this->generator()->url($generator, true) ?>" alt="" id="preview" class="img-responsive" />
        </div>
    </div>

</section>