<?php echo $this->headTitle()->prepend($generator->getName()) ?>

<?php echo $this->form()->openTag($form) ?>
    <section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

        <div class="widget">
                <h3 class="widget-title"><?php echo $generator->getName(); ?></h3>

                <div class="meme clearfix">
                    <img src="<?php echo $this->prototype()->url($generator, true) ?>" id="preview" alt="" class="img-responsive" />
                </div>
                
                <!-- #CSRF -->
                <?php echo $this->formInput($form->get('csrf')) ?>

                <!-- #Upper text -->
                <div class="form-row">
                    <div class="input-group">
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-arrow-up"></span>
                        </span>
                        <?php echo $this->formInput($form->get('top')) ?>
                    </div>

                    <?php echo $this->formElementErrors($form->get('top')) ?>
                </div>

                <!-- #Bottom text -->
                <div class="form-row">
                    <div class="input-group">
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-arrow-down"></span>
                        </span>
                        <?php echo $this->formInput($form->get('bottom')) ?>
                    </div>

                    <?php echo $this->formElementErrors($form->get('bottom')) ?>
                </div>

                <!-- #Token -->
                <?php echo $this->formHidden($form->get('token')) ?>
                
                <?php echo $this->formElementErrors($form->get('token')) ?>
        </div>

    </section>

    <section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">       

        <div class="widget">
            <h3 class="widget-title">Publish or download!</h3>

            <div class="widget-content">
                When you are done with your meme you can download it or publish it on our page!
            </div>

            <!-- #Download / Publish -->
            <ul class="publish-group">
                <li><?php echo $this->formButton($form->get('publish')) ?></li>
                <li><?php echo $this->formButton($form->get('download')) ?></li>
            </ul>
        </div>

    </section>
<?php echo $this->form()->closeTag() ?>