<?php
    $form = $this->form;
    $form->setAttribute(
        'action',
        $this->url('edit', array('slug' => $generator->getSlug()))
    );
?>

<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
    
    <div class="widget">
        <?php echo $this->form()->openTag($form) ?>
        <h3 class="login-title">Meme generator</h3>
        
        <div class="meme clearfix">
            <img src="<?php echo $this->generator()->url($generator, true) ?>" alt="" class="img-responsive" />
        </div>
        
            <!-- #Upper text -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-arrow-up"></span>
                    </span>
                    <?php echo $this->formInput($form->get('top')) ?>
                </div>
                
                <?php echo $this->formElementErrors($form->get('top')) ?>
            </div>      
            
            <!-- #Bottom text -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-arrow-down"></span>
                    </span>
                    <?php echo $this->formInput($form->get('bottom')) ?>
                </div>
                
                <?php echo $this->formElementErrors($form->get('bottom')) ?>
            </div>         
        <?php echo $this->form()->closeTag() ?>         
    </div>

</section>

<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">          

    <div class="widget">
        <h3 class="login-title">Save your image or publish it on the site!</h3>

        <div class="contact-desc">
            You can easily save image to local storage or
            <br><br>
            post it on the site and make it visible to other visitors!
        </div>
    </div>

</section>