<?php echo $this->headTitle()->prepend('Create your own') ?>

<section class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    
    <div class="widget">
        <h3 class="widget-title">Select your favorite</h3>

        <div class="meme-grid clearfix">
            <?php foreach($generator as $index=>$g):?>

            <a href="<?php echo $this->url('edit', array('slug' => $g->getSlug())) ?>" class="meme-img">
                <img src="<?php echo $this->prototype()->url($g) ?>" alt="" class="img-responsive" />
            </a>
        
            <?php endforeach ?>
        </div>
        
    </div>

</section>