<section class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    
    <div class="widget">
        <h3 class="login-title">Select your favorite</h3>

            <?php $i=0; foreach ($generator as $g): $i++;?>
        
            <?php if ($i%5 == 0) echo '<div class="form-row">' ?>
                <a href="<?php echo $this->url('edit', array('slug' => $g->getSlug())) ?>" class="meme-img">
                    <img src="<?php echo $this->generator()->url($g) ?>" alt="" class="img-responsive generator" />
                </a>                          
             <?php if ($i%5 == 0) echo '</div>' ?>    
        
            <?php endforeach ?>
            
    </div>

</section>