<section class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    
    <div class="widget">
        <h3 class="login-title">Select your favorite</h3>

            <div class="form-row">
                <a href="<?php echo $this->url('edit', array('image' => 'name')) ?>" class="meme-img">
                    <img src="http://i.memeful.com/template_thumbnails/522acc5982a5f/ymRP0RL.jpg" alt="" class="img-responsive generator" />
                </a>
                
                <a href="#" class="meme-img">
                    <img src="http://i.memeful.com/template_thumbnails/53167cbaaa16e/0Mx3JwL.jpg" alt="" class="img-responsive generator" />
                </a>
                
                <a href="#" class="meme-img">
                    <img src="http://i.memeful.com/template/51de8b9011fce/ZVMVqw2.jpg" alt="" class="img-responsive generator" />
                </a>                     
        
                <a href="#" class="meme-img">
                    <img src="http://i.memeful.com/template/51de8bc39da05/jGwD6R4.jpg" alt="" class="img-responsive generator" />
                </a>                  
    
                <a href="#" class="meme-img">
                    <img src="http://i.memeful.com/template_thumbnails/521ee7a0bf16c/LR8ZQwv.jpg" alt="" class="img-responsive generator" />
                </a>                         
            </div>       
            
            <div class="form-row">
                <a href="#" class="meme-img">
                    <img src="http://i.memeful.com/template/51de8b88d83c7/Z1RXLRp.jpg" alt="" class="img-responsive generator" />
                </a>  
                
                
                <a href="#" class="meme-img">
                    <img src="http://i.memeful.com/template_thumbnails/53167cbaaa16e/0Mx3JwL.jpg" alt="" class="img-responsive generator" />
                </a>
                
                <a href="#" class="meme-img">
                    <img src="http://i.memeful.com/template/51de8b9011fce/ZVMVqw2.jpg" alt="" class="img-responsive generator" />
                </a>                     
        
                <a href="#" class="meme-img">
                    <img src="http://i.memeful.com/template/51de8bc39da05/jGwD6R4.jpg" alt="" class="img-responsive generator" />
                </a>                  
    
                <a href="#" class="meme-img">
                    <img src="http://i.memeful.com/template_thumbnails/521ee7a0bf16c/LR8ZQwv.jpg" alt="" class="img-responsive generator" />
                </a>                   
            </div>        
       
            <div class="form-row">
                <a href="#" class="meme-img">
                    <img src="http://i.memeful.com/template/51de8b88d83c7/Z1RXLRp.jpg" alt="" class="img-responsive generator" />
                </a>  
                
                
                <a href="#" class="meme-img">
                    <img src="http://i.memeful.com/template_thumbnails/53167cbaaa16e/0Mx3JwL.jpg" alt="" class="img-responsive generator" />
                </a>
                
                <a href="#" class="meme-img">
                    <img src="http://i.memeful.com/template/51de8b9011fce/ZVMVqw2.jpg" alt="" class="img-responsive generator" />
                </a>                     
        
                <a href="#" class="meme-img">
                    <img src="http://i.memeful.com/template/51de8bc39da05/jGwD6R4.jpg" alt="" class="img-responsive generator" />
                </a>                  
    
                <a href="#" class="meme-img">
                    <img src="http://i.memeful.com/template_thumbnails/521ee7a0bf16c/LR8ZQwv.jpg" alt="" class="img-responsive generator" />
                </a>                   
            </div>            
    </div>

</section>