<?php echo $this->headTitle()->prepend('Publish') ?>

<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

    <div class="widget">
        <?php echo $this->form()->openTag($publishForm) ?>

            <h3 class="widget-title">Publish your meme ...</h3>

            <!-- #CSRF -->
            <?php echo $this->formHidden($publishForm->get('csrf')) ?>
            
            <!-- #Name -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-tag"></span>
                    </span>
                    <?php echo $this->formInput($publishForm->get('name')) ?>
                </div>

                <?php echo $this->formElementErrors($publishForm->get('name')) ?>
            </div>

            <!-- #Category -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-flag"></span>
                    </span> 
                    <?php echo $this->formSelect($publishForm->get('category_id')) ?>
                </div>

                <?php echo $this->formElementErrors($publishForm->get('category_id')) ?>
            </div>

            <!-- #Token -->
            <?php echo $this->formHidden($publishForm->get('token')) ?>

            <div class="input-group">
                <?php echo $this->formButton($publishForm->get('submit')) ?>
            </div>

        <?php echo $this->form()->closeTag() ?>
    </div>
    
    <?php if (isset($tempFile)): ?>
    
        Uploaded file:
        <?php echo $tempFile ?>
    
    <?php endif ?>

</section>

<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">          

    <div class="widget">
        <h3 class="widget-title">Share your meme with others!</h3>

        <div class="widget-content">
            Publish your meme on our page right now.<br />
            <br />
            You can also share it on Facebook, Twitter, GooglePlus or with email.<br />
        </div>
    </div>

</section>