
<?php if ($this->pageCount): ?>
    <ul id="pagination" class="pagination clearfix">
        
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
            <li class="pagination-big">
                <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous; ?>">&laquo;</a>
            </li>
            <li class="pagination-small">
                <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous; ?>">Previous</a>
            </li>
        <?php else: ?>
            <li class="disabled pagination-big">
                <a href="#">&laquo;</a>
            </li>
            <li class="pagination-small">
                <a href="#">Previous</a>
            </li>            
        <?php endif ?>
            
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
        
            <?php if ($page != $this->current): ?>
                <li class="pagination-big">
                    <a href="<?php echo $this->url($this->route);?>?page=<?php echo $page; ?>">
                        <?php echo $page; ?>
                    </a>
                </li>
            <?php else: ?>
                <li class="active pagination-big">
                    <a href="#"><?php echo $page; ?></a>
                </li>
            <?php endif ?>
            
        <?php endforeach ?>

        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
            <li class="pagination-big">
                <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->next; ?>">&raquo;</a>
            </li>
            <li class="pagination-small">
                <a href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->next; ?>">Next</a>                
            </li>
        <?php else: ?>
            <li class="disabled pagination-big">
                <a href="#">&raquo;</a>
            </li>
            <li class="pagination-small">
                <a href="#">Next</a>
            </li>            
        <?php endif ?>
            
    </ul>
<?php endif ?>