<section class="col-lg-8 col-md-8 col-sm-8 col-xs-12 meme-listing">
    
    <h3 class="category-name"><?php echo $category->getName() ?></h3>
    
    <?php if (count($media) === 0): ?>
    
        There is no media in this category.
        
    <?php endif ?>
    
    <?php foreach ($media as $m): ?>
        
        <article class="meme clearfix" data-slug="<?php echo $m->getSlug() ?>">
            <div class="meme-title">
                <a href="<?php echo $this->url('gag/details', array('slug' => $m->getSlug())) ?>">
                    <?php echo $m->getName() ?>
                </a>
            <div class="meme-points">
                Points: <?php echo $this->media()->getPoints($m) ?>,
                Comments: <?php echo $this->media()->getComments($m) ?>
            </div>               
            </div>
            <a href="<?php echo $this->url('gag/details', array('slug' => $m->getSlug())) ?>" class="meme-img">
                <img src="<?php echo $this->media()->url($m) ?>" alt="" class="img-responsive" />
            </a>
            <div class="meme-author">
                Posted by <strong><?php echo $this->user()->findById($m->getUserId())->getUsername() ?></strong>
            </div>
            <ul class="meme-action clearfix">
                <?php
                    $response = $this->media()->getResponse($m);
                    
                    if(!$this->zfcUserIdentity()):
                ?>
                    <li class="btn-group">
                        <a href="<?php echo $this->url('zfcuser/login') ?>" class="btn btn-default" data-type="up">
                            <span class="glyphicon glyphicon-chevron-up"></span>
                        </a>
                        <a href="<?php echo $this->url('zfcuser/login') ?>" class="btn btn-default" data-type="down">
                            <span class="glyphicon glyphicon-chevron-down"></span>
                        </a>
                    </li>
                <?php elseif ($response !== false && $this->media()->isResponseDown($response)): ?>
                    <li class="btn-group" data-trigger="response">
                        <a href="javascript:void(0);" class="btn btn-default" data-type="up">
                            <span class="glyphicon glyphicon-chevron-up"></span>
                        </a>
                        <a href="javascript:void(0);" class="btn btn-default response-selected" data-type="down">
                            <span class="glyphicon glyphicon-chevron-down"></span>
                        </a>
                    </li>
                <?php elseif ($response !== false && $this->media()->isResponseUp($response)): ?>
                    <li class="btn-group" data-trigger="response">
                        <a href="javascript:void(0);" class="btn btn-default response-selected" data-type="up">
                            <span class="glyphicon glyphicon-chevron-up"></span>
                        </a>
                        <a href="javascript:void(0);" class="btn btn-default" data-type="down">
                            <span class="glyphicon glyphicon-chevron-down"></span>
                        </a>
                    </li>
                <?php else: ?>
                    <li class="btn-group" data-trigger="response">
                        <a href="javascript:void(0);" class="btn btn-default" data-type="up">
                            <span class="glyphicon glyphicon-chevron-up"></span>
                        </a>
                        <a href="javascript:void(0);" class="btn btn-default" data-type="down">
                            <span class="glyphicon glyphicon-chevron-down"></span>
                        </a>
                    </li>
                <?php endif ?>
                <li>
                    <a href="#" data-type="facebook" data-url="<?php echo $this->basePath() . $this->url('gag/details', array('slug' => $m->getSlug())) ?>" data-description="Click to see the pic and write a comment ..." data-title="<?php echo $m->getName() ?>" data-media="<?php echo $this->media()->url($m) ?>" class="btn btn-facebook">Facebook</a>
                </li>
                <li>
                    <a href="#" data-type="twitter" data-url="<?php echo $this->basePath() . $this->url('gag/details', array('slug' => $m->getSlug())) ?>" data-description="<?php echo $m->getName() ?>" data-via="GAGchan" data-media="<?php echo $this->media()->url($m) ?>" class="btn btn-twitter">Twitter</a>
                </li>
                <li>
                    <a data-clipboard-text="<?php echo $this->basePath() . $this->url('gag/details', array('slug' => $m->getSlug())) ?>"  class="btn btn-default zeroclipboard">
                        <span class="glyphicon glyphicon-link"></span>
                    </a>
                </li>
            </ul>
        </article>
        
    <?php endforeach ?>
    
    <?php echo $this->paginationControl($media, 'sliding', array('partial/paginator.phtml', 'Media'), array('route' => 'home')) ?>
        
</section>

<section id="sidebar" class="col-lg-4 col-md-4 col-sm-4 hidden-xs">
    <div class="widget meme-listing">
        <h3 class="widget-title">Featured</h3>

        <article class="meme">
            <a href="#" class="meme-img">
                <img src="http://d3dsacqprgcsqh.cloudfront.net/photo/aKzR036_460s.jpg" alt="" class="img-responsive" />
            </a>
            <div class="meme-title">
                <a href="#">This is a meme with a very very very very long meme name</a>
            </div>
        </article>

        <article class="meme">
            <a href="#" class="meme-img">
                <img src="http://d3dsacqprgcsqh.cloudfront.net/photo/aKzR036_460s.jpg" alt="" class="img-responsive" />
            </a>
            <div class="meme-title">
                <a href="#">This is a meme with a very very very very long meme name</a>
            </div>
        </article>

        <article class="meme">
            <a href="#" class="meme-img">
                <img src="http://d3dsacqprgcsqh.cloudfront.net/photo/aKzR036_460s.jpg" alt="" class="img-responsive" />
            </a>
            <div class="meme-title">
                <a href="#">This is a meme with a very very very very long meme name</a>
            </div>
        </article>
    </div>
</section>