<?php echo $this->headTitle()->prepend('Privacy policy') ?>

<section class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Privacy Policy
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            This Privacy Policy governs the manner in which GAGchan collects,
            uses, maintains and discloses information collected from users
            (each, a "User") of the www.gagchan.com website ("Site"). This
            privacy policy applies to the Site and all products and services
            offered by GAGchan.
        </div> <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Personal identification information
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            We may collect personal identification information from Users in a
            variety of ways, including, but not limited to, when Users visit our
            site, register on the site, subscribe to the newsletter, fill out a
            form, and in connection with other activities, services, features or
            resources we make available on our Site. Users may be asked for, as
            appropriate, email address. Users may, however, visit our Site
            anonymously. We will collect personal identification information
            from Users only if they voluntarily submit such information to us.
            Users can always refuse to supply personally identification
            information, except that it may prevent them from engaging in
            certain Site related activities.
        </div> <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Non-personal identification information
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            We may collect non-personal identification information about Users
            whenever they interact with our Site. Non-personal identification
            information may include the browser name, the type of computer and
            technical information about Users means of connection to our Site,
            such as the operating system and the Internet service providers
            utilized and other similar information.
        </div> <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Web browser cookies
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            Our Site may use "cookies" to enhance User experience. User's web
            browser places cookies on their hard drive for record-keeping
            purposes and sometimes to track information about them. User may
            choose to set their web browser to refuse cookies, or to alert you
            when cookies are being sent. If they do so, note that some parts of
            the Site may not function properly.
        </div> <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                How we use collected information
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            <strong>GAGchan may collect and use Users personal information for
            the following purposes:</strong>
        </div> <!-- /.panel-body -->
        
        <ul class="list-group">
            <li class="list-group-item list-group-item-info">
                &#8212; <strong>To improve customer service</strong>
            </li>
            <li class="list-group-item">
                Information you provide helps us respond to your customer
                service requests and support needs more efficiently.
            </li>
            <li class="list-group-item list-group-item-info">
                &#8212; <strong>To personalize user experience</strong>
            </li>
            <li class="list-group-item">
                We may use information in the aggregate to understand how our
                Users as a group use the services and resources provided on
                our Site.
            </li>
            <li class="list-group-item list-group-item-info">
                &#8212; <strong>To improve our Site</strong>
            </li>
            <li class="list-group-item">
                We may use feedback you provide to improve our products
                and services.
            </li>
            <li class="list-group-item list-group-item-info">
                &#8212; <strong>To send periodic emails</strong>
            </li>
            <li class="list-group-item">
                We may use the email address to send User information and
                updates pertaining to their order. It may also be used to
                respond to their inquiries, questions, and/or other requests.
                If User decides to opt-in to our mailing list, they will receive
                emails that may include company news, updates, related product
                or service information, etc. If at any time the User would like
                to unsubscribe from receiving future emails, we include detailed
                unsubscribe instructions at the bottom of each email.
            </li>
        </ul>
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                How we protect your information
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            We adopt appropriate data collection, storage and processing
            practices and security measures to protect against unauthorized
            access, alteration, disclosure or destruction of your personal
            information, username, password, transaction information and data
            stored on our Site.<br />
            <br />
            Sensitive and private data exchange between the Site and its Users
            happens over a SSL secured communication channel and is encrypted
            and protected with digital signatures.<br />
        </div> <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Sharing your personal information
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            We do not sell, trade, or rent Users personal identification
            information to others. We may share generic aggregated demographic
            information not linked to any personal identification information
            regarding visitors and users with our business partners, trusted
            affiliates and advertisers for the purposes outlined above.
        </div> <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Third party websites
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            Users may find advertising or other content on our Site that link
            to the sites and services of our partners, suppliers, advertisers,
            sponsors, licensors and other third parties. We do not control the
            content or links that appear on these sites and are not responsible
            for the practices employed by websites linked to or from our Site.
            In addition, these sites or services, including their content and
            links, may be constantly changing. These sites and services may have
            their own privacy policies and customer service policies. Browsing
            and interaction on any other website, including websites which have
            a link to our Site, is subject to that website's own terms
            and policies.
        </div> <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Advertising
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            Ads appearing on our site may be delivered to Users by advertising
            partners, who may set cookies. These cookies allow the ad server to
            recognize your computer each time they send you an online
            advertisement to compile non personal identification information
            about you or others who use your computer. This information allows
            ad networks to, among other things, deliver targeted advertisements
            that they believe will be of most interest to you. This privacy
            policy does not cover the use of cookies by any advertisers.
        </div> <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Google Adsense
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            Some of the ads may be served by Google. Google's use of the DART
            cookie enables it to serve ads to Users based on their visit to our
            Site and other sites on the Internet. DART uses "non personally
            identifiable information" and does NOT track personal information
            about you, such as your name, email address, physical address, etc.
            You may opt out of the use of the DART cookie by visiting the
            Google ad and content network privacy policy at
            http://www.google.com/privacy_ads.html
        </div> <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Compliance with children's online privacy protection act
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            Protecting the privacy of the very young is especially important.
            For that reason, we never collect or maintain information at our
            Site from those we actually know are under 13, and no part of our
            website is structured to attract anyone under 13.
        </div> <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Changes to this privacy policy
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            GAGchan has the discretion to update this privacy policy at any
            time. When we do, we will revise the updated date at the bottom of
            this page and send you an email. We encourage Users to frequently
            check this page for any changes to stay informed about how we are
            helping to protect the personal information we collect. You
            acknowledge and agree that it is your responsibility to review this
            privacy policy periodically and become aware of modifications.
        </div> <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Your acceptance of these terms
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            By using this Site, you signify your acceptance of this policy. If
            you do not agree to this policy, please do not use our Site. Your
            continued use of the Site following the posting of changes to this
            policy will be deemed your acceptance of those changes.
        </div> <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Contacting us
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            If you have any questions about this Privacy Policy, the practices
            of this site, or your dealings with this site, please contact us through
            <a href="<?php echo $this->url('contact') ?>"> contact form</a>.
        </div> <!-- /.panel-body -->
        
    </div> <!-- /.panel -->

</section>
