<?php echo $this->headTitle()->prepend('Privacy policy') ?>

<section class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                What is this Privacy Policy for?
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            This privacy policy is for this web site is served by GAGchan and
            governs the privacy of its users who choose to use it.<br />
            <br />
            The policy sets out the different areas where user privacy
            is concerned and outlines the obligations & requirements of
            the users, the web site and web site owners. Furthermore the way
            this web site processes, stores and protects user data and
            information will also be detailed within this policy.<br />
        </div> <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                The Website
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            GAGchan takes a proactive approach to user privacy and ensures that
            necessary steps are taken to protect the privacy of its users
            throughout their visiting experience.<br />
        </div> <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Cookies
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            Cookies are files saved to the users computers hard drive that track,
            save and store information about the users interactions and usage of
            the website.<br />
            <br />
            GAGchan uses cookies to better the users experience and help
            identify and track visitor while visiting the web site.<br />
        </div> <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Security & Personal Information
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            Users contacting GAGchan.com and/or it's owners do so at their
            own discretion and provide any such personal details requested
            at their own risk. Your personal information is kept private and
            stored securely until a time it is no longer required or has no use.<br />
            Your details are not passed on to any third parties.<br />
        </div> <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Ads
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            Ads appearing on any GAGchan web sites may be delivered to users
            by advertising partners, who may set cookies. These cookies allow
            the ad server to recognize your computer each time they send you
            an online advertisement to compile information about you or
            others who use your computer. This information allows ad
            networks to, among other things, deliver targeted advertisements
            that they believe will be of most interest to you.<br />
        </div> <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Contact
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        
        <div class="panel-body">
            If you have any questions about this privacy policy or our sites in general, please <a href="<?php echo $this->url('contact') ?>">contact us</a>.<br />
        </div> <!-- /.panel-body -->
        
    </div> <!-- /.panel -->

</section>
