<?php echo $this->headTitle()->prepend('Privacy policy') ?>

<section class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    
    <div class="widget">
        <h3 class="widget-title">What is this Privacy Policy for?</h3>
        
        <div class="form-row">
            This privacy policy is for this web site is served by GAGchan and
            governs the privacy of its users who choose to use it.<br />
            <br />
            The policy sets out the different areas where user privacy
            is concerned and outlines the obligations & requirements of
            the users, the web site and web site owners. Furthermore the way
            this web site processes, stores and protects user data and
            information will also be detailed within this policy.<br />
        </div>
    </div>
    
    <div class="widget">
        <h3 class="widget-title">The Web site</h3>
        
        <div class="form-row">
            GAGchan take a proactive approach to user
            privacy and ensure the necessary steps are taken to protect the
            privacy of its users throughout their visiting experience.<br />
        </div>
    </div>
    
    <div class="widget">         
        <h3 class="widget-title">Cookies</h3>
        
        <div class="form-row">
            Cookies are small files saved to the users computers hard drive that
            track, save and store information about the users interactions and
            usage of the web site.<br />
            <br />
            GAGchan uses cookies to better the users experience and help
            identify and track visitor while visiting the web site.<br />
        </div>
    </div>
    
    <div class="widget">
        <h3 class="widget-title">Security & Personal Information</h3>
        
        <div class="form-row">
            Users contacting GAGchan.com and/or it's owners do so at their
            own discretion and provide any such personal details requested
            at their own risk. Your personal information is kept private and
            stored securely until a time it is no longer required or has no use.<br />
            Your details are not passed on to any third parties.<br />
        </div>
    </div>
    
    <div class="widget">
        <h3 clas="widget-title">Ads</h3>
        
        <div class="form-row">
            Ads appearing on any GAGchan web sites may be delivered to users
            by advertising partners, who may set cookies. These cookies allow
            the ad server to recognize your computer each time they send you
            an online advertisement to compile information about you or
            others who use your computer. This information allows ad
            networks to, among other things, deliver targeted advertisements
            that they believe will be of most interest to you.<br />
        </div>
    </div>
    
    <div class="widget">
        <h3 clas="widget-title">Contact</h3>
        
        <div class="form-row">
            If you have any questions about this privacy policy or our sites in general, please <a href="<?php echo $this->url('contact') ?>">contact us</a>.<br />
        </div>
    </div>

</section>
