<?php echo $this->headTitle()->prepend('Terms of Use') ?>

<section class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Terms of Use
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            If you require any more information or have any questions about our
            Terms of Use, please feel free to contact us through
            <a href="<?php echo $this->url('contact') ?>">contact form</a>.
        </div>   <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Introduction
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            These terms and conditions govern your use of this website; by using
            this website, you accept these terms and conditions in full and
            without reservation. If you disagree with these terms and conditions
            or any part of these terms and conditions, you must not use
            this website.<br />
            <br />
            You must be at least 13 [thirteen] years of age to use this website.
            By using this website and by agreeing to these terms and conditions,
            you warrant and represent that you are at least 13 years of age.<br />
        </div>   <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                License to use website
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            Unless otherwise stated, www.gagchan.com and/or its licensors own
            the intellectual property rights published on this website and
            materials used on www.gagchan.com. Subject to the license below,
            all these intellectual property rights are reserved.<br />
            <br />
            You may view, download for caching purposes only, and print pages,
            files or other content from the website for your own personal use,
            subject to the restrictions set out below and elsewhere in these
            terms and conditions.<br />
            <br />
            You must not:<br />
        </div>   <!-- /.panel-body -->
        
        <ul class="list-group">
            <li class="list-group-item">
                &#8212; republish material from this website in neither print nor
                digital media or documents (including republication on another
                website);
            </li>
            <li class="list-group-item">
                &#8212; sell, rent or sub-license material from the website;
            </li>
            <li class="list-group-item">
                &#8212; show any material from the website in public;
            </li>
            <li class="list-group-item">
                &#8212; reproduce, duplicate, copy or otherwise exploit material on
                this website for a commercial purpose;
            </li>
            <li class="list-group-item">
                &#8212; edit or otherwise modify any material on the website;
            </li>
            <li class="list-group-item">
                &#8212; redistribute material from this website - except for content
                specifically and expressly made available for redistribution; or
            </li>
            <li class="list-group-item">
                &#8212; republish or reproduce any part of this website through the use
                of iframes or screenscrapers.
            </li>
        </ul>
        
        <div class="panel-body">
            Where content is specifically made available for redistribution, it
            may only be redistributed within your organisation.
        </div>   <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Acceptable use
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            You must not use this website in any way that causes, or may cause,
            damage to the website or impairment of the availability or
            accessibility of www.gagchan.com or in any way which is unlawful,
            illegal, fraudulent or harmful, or in connection with any unlawful,
            illegal, fraudulent or harmful purpose or activity.<br />
            <br />
            You must not use this website to copy, store, host, transmit, send,
            use, publish or distribute any material which consists of (or is
            linked to) any spyware, computer virus, Trojan horse, worm,
            keystroke logger, rootkit or other malicious computer software.<br />
            <br />
            You must not conduct any systematic or automated data collection
            activities on or in relation to this website without
            www.gagchan.com's express written consent.<br />
            <br />
            This includes:<br />
        </div>   <!-- /.panel-body -->

        <ul class="list-group">
            <li class="list-group-item">
                &#8212; scraping
            </li>
            <li class="list-group-item">
                &#8212; data mining
            </li>
            <li class="list-group-item">
                &#8212; data extraction
            </li>
            <li class="list-group-item">
                &#8212; data harvesting
            </li>
            <li class="list-group-item">
                &#8212; 'framing' (iframes)
            </li>
            <li class="list-group-item">
                &#8212; Article 'Spinning'
            </li>
        </ul>

        <div class="panel-body">
            You must not use this website or any part of it to transmit or send
            unsolicited commercial communications.<br />
            <br />
            You must not use this website for any purposes related to marketing
            without the express written consent of www.gagchan.com.<br />
        </div>   <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Restricted access
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->

        <div class="panel-body">
            Access to certain areas of this website is restricted.
            www.gagchan.com reserves the right to restrict access to certain
            areas of this website, or at our discretion, this entire website.
            www.gagchan.com may change or modify this policy without notice.<br />
            <br />
            If www.gagchan.com provides you with a user ID and password to
            enable you to access restricted areas of this website or other
            content or services, you must ensure that the user ID and password
            are kept confidential. You alone are responsible for your password
            and user ID security.<br />
            <br />
            www.gagchan.com may disable your user ID and password at
            www.gagchan.com's sole discretion without notice or explanation.<br />
        </div>   <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                User content
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->

        <div class="panel-body">
            In these terms and conditions, “your user content” means material
            (including without limitation text, images, audio material, video
            material and audio-visual material) that you submit to this website,
            for whatever purpose.<br />
            <br />
            You grant to www.gagchan.com a worldwide, irrevocable,
            non-exclusive, royalty-free license to use, reproduce, adapt,
            publish, translate and distribute your user content in any existing
            or future media. You also grant to www.gagchan.com the right to
            sub-license these rights, and the right to bring an action for
            infringement of these rights.<br />
            <br />
            Your user content must not be illegal or unlawful, must not
            infringe any third party's legal rights, and must not be capable of
            giving rise to legal action whether against you or www.gagchan.com
            or a third party (in each case under any applicable law).<br />
            <br />
            You must not submit any user content to the website that is or has
            ever been the subject of any threatened or actual legal proceedings
            or other similar complaint.<br />
            <br />
            www.gagchan.com reserves the right to edit or remove any material
            submitted to this website, or stored on the servers of
            www.gagchan.com, or hosted or published upon this website.<br />
            <br />
            www.gagchan.com's rights under these terms and conditions in
            relation to user content, www.gagchan.com does not undertake to
            monitor the submission of such content to, or the publication of
            such content on, this website.<br />
        </div>   <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                No warranties
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            This website is provided “as is” without any representations or
            warranties, express or implied. www.gagchan.com makes no
            representations or warranties in relation to this website or the
            information and materials provided on this website.<br />
            <br />
            Without prejudice to the generality of the foregoing paragraph,
            www.gagchan.com does not warrant that:<br />
        </div>   <!-- /.panel-body -->

        <ul class="list-group">
            <li class="list-group-item">
                &#8212; this website will be constantly available, or available
                at all; or
            </li>
            <li class="list-group-item">
                &#8212; the information on this website is complete, true,
                accurate or non-misleading.
            </li>
        </ul>

        <div class="panel-body">
            Nothing on this website constitutes, or is meant to constitute,
            advice of any kind. If you require advice in relation to any legal,
            financial or medical matter you should consult an
            appropriate professional.
        </div>   <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Limitations of liability
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            www.gagchan.com will not be liable to you (whether under the law of
            contact, the law of torts or otherwise) in relation to the contents
            of, or use of, or otherwise in connection with, this website:
        </div>   <!-- /.panel-body -->

        <ul class="list-group">
            <li class="list-group-item">
                &#8212; to the extent that the website is provided
                free-of-charge, for any direct loss;
            </li>
            <li class="list-group-item">
                &#8212; for any indirect, special or consequential loss; or
            </li>
            <li class="list-group-item">
                &#8212; for any business losses, loss of revenue, income,
                profits or anticipated savings, loss of contracts or business
                relationships, loss of reputation or goodwill, or loss or
                corruption of information or data.
            </li>
        </ul>

        <div class="panel-body">
            These limitations of liability apply even if www.gagchan.com has
            been expressly advised of the potential loss.
        </div>   <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Exceptions
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            Nothing in this website disclaimer will exclude or limit any
            warranty implied by law that it would be unlawful to exclude or
            limit; and nothing in this website disclaimer will exclude or limit
            the liability of GAGchan in respect of any:
        </div>   <!-- /.panel-body -->

        <ul class="list-group">
            <li class="list-group-item">
                &#8212; death or personal injury caused by the negligence of
                www.gagchan.com or its agents, employees or shareholders/owners;
            </li>
            <li class="list-group-item">
                &#8212; fraud or fraudulent misrepresentation on the part of
                www.gagchan.com; or
            </li>
            <li class="list-group-item">
                &#8212; matter which it would be illegal or unlawful for
                www.gagchan.com to exclude or limit, or to attempt or purport
                to exclude or limit, its liability.
            </li>
        </ul>
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Reasonableness
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            By using this website, you agree that the exclusions and
            limitations of liability set out in this website disclaimer
            are reasonable.<br />
            <br />
            If you do not think they are reasonable, you must not use
            this website.<br />
        </div>   <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Other parties
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            You accept that, as a limited liability entity, www.gagchan.com has
            an interest in limiting the personal liability of its officers and
            employees. You agree that you will not bring any claim personally
            against www.gagchan.com's officers or employees in respect of any
            losses you suffer in connection with the website.<br />
            <br />
            Without prejudice to the foregoing paragraph, you agree that the
            limitations of warranties and liability set out in this website
            disclaimer will protect www.gagchan.com's officers, employees,
            agents, subsidiaries, successors, assigns and sub-contractors as
            well as www.gagchan.com.<br />
        </div>   <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Unenforceable provisions
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            If any provision of this website disclaimer is, or is found to be,
            unenforceable under applicable law, that will not affect the
            enforceability of the other provisions of this website disclaimer.
        </div>   <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Indemnity
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            You hereby indemnify www.gagchan.com and undertake to keep
            www.gagchan.com indemnified against any losses, damages, costs,
            liabilities and expenses (including without limitation legal
            expenses and any amounts paid by www.gagchan.com to a third party
            in settlement of a claim or dispute on the advice of
            www.gagchan.com's legal advisers) incurred or suffered by
            www.gagchan.com arising out of any breach by you of any provision
            of these terms and conditions, or arising out of any claim that you
            have breached any provision of these terms and conditions.
        </div>   <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Breaches of these terms and conditions
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            Without prejudice to www.gagchan.com's other rights under these
            terms and conditions, if you breach these terms and conditions in
            any way, www.gagchan.com may take such action as www.gagchan.com
            deems appropriate to deal with the breach, including suspending
            your access to the website, prohibiting you from accessing the
            website, blocking computers using your IP address from accessing
            the website, contacting your internet service provider to request
            that they block your access to the website and/or bringing court
            proceedings against you.
        </div>   <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Variation
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            www.gagchan.com may revise these terms and conditions from
            time-to-time. Revised terms and conditions will apply to the use
            of this website from the date of the publication of the revised
            terms and conditions on this website. Please check this page
            regularly to ensure you are familiar with the current version.
        </div>   <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Assignment
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            www.gagchan.com may transfer, sub-contract or otherwise deal with
            www.gagchan.com's rights and/or obligations under these terms and
            conditions without notifying you or obtaining your consent.<br />
            <br />
            You may not transfer, sub-contract or otherwise deal with your
            rights and/or obligations under these terms and conditions.<br />
        </div>   <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Severability
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            If a provision of these terms and conditions is determined by any
            court or other competent authority to be unlawful and/or
            unenforceable, the other provisions will continue in effect.
            If any unlawful and/or unenforceable provision would be lawful or
            enforceable if part of it were deleted, that part will be deemed to
            be deleted, and the rest of the provision will continue in effect.
        </div>   <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Entire agreement
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            These terms and conditions, together with www.gagchan.com's
            Privacy Policy constitute the entire agreement between you and
            www.gagchan.com in relation to your use of this website, and
            supersede all previous agreements in respect of your use
            of this website.
        </div>   <!-- /.panel-body -->
        
    </div> <!-- /.panel -->
    
    <div class="panel panel-default">
        
        <div class="panel-heading">
            
            <div class="panel-title">
                Law and jurisdiction
            </div> <!-- /.panel-title -->
            
        </div> <!-- /.panel-heading -->
        
        <div class="panel-body">
            These terms and conditions will be governed by and construed in
            accordance with the laws of SLOVENIA, and any disputes relating
            to these terms and conditions will be subject to the exclusive
            jurisdiction of the courts of SLOVENIA.
        </div>   <!-- /.panel-body -->
        
    </div> <!-- /.panel -->

</section>
