<?php echo $this->headTitle()->prepend('Terms of Use') ?>

<section class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    
    <div class="widget">
        <h3 class="widget-title">Terms of Use</h3>
        
        <div class="form-row">
            By using our services you must agree that the any content  you have
            or will publish belongs to you and can be modified by our team and
            it can be displayed in public on any of our services.<br />
            <br />
            We do not taking any responsibility for the uploaded media. We reserve
            the right to edit any image you  might upload at any time.<br />
            <br />
            You must also agree to receive any notification messages from us to
            the email address, which you have used during the sign up (through
            our sign up form or using your social network account).<br />
        </div>      
    </div>

</section>
