<?php echo $this->doctype(); ?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('GAGchan')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    ?>
    
    <!-- Favicon -->
    <?php echo $this->headLink(array('rel'  => 'favicon', 'type' => 'image/png', 'href' => $this->basePath() . '/imgages/favicon.png')) ?>

    <!-- Styles -->
    <?php echo $this->headLink()
        ->prependStylesheet($this->basePath() . '/css/layout.css')
        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
    ?>

    <!-- Google Fonts -->
    <?php echo $this->headLink()
        ->prependStylesheet('http://fonts.googleapis.com/css?family=Roboto+Slab:400,700&subset=latin,latin-ext')
        ->prependStylesheet('http://fonts.googleapis.com/css?family=Noto+Sans:400,700,400italic,700italic&subset=latin,latin-ext')
    ?>

    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/bootstrap.min.js')
        ->prependFile('https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js', 'text/javascript')
        ->prependFile('https://oss.maxcdn.com/respond/1.4.2/respond.min.js',   'text/javascript', array('conditional' => 'lt IE 9'))
        ->prependFile('https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js', 'text/javascript', array('conditional' => 'lt IE 9'))
    ?>
</head>
<body>
       <!-- #Navigation Bar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        
        <div class="container">
            
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="index.html"></a>
            </div><!--/.navbar-header -->
            
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="index.html">Latest</a>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Browse by category <span class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                          <li><a href="category.html#gif">GIF</a></li>
                          <li><a href="category.html#cute">Cute</a></li>
                          <li><a href="category.html#geeky">Geeky</a></li>
                          <li><a href="category.html#cosplay">Cosplay</a></li>
                          <li><a href="category.html#meme">Meme</a></li>
                          <li><a href="category.html#timely">Timely</a></li>
                          <li><a href="category.html#girl">Girl</a></li>
                          <li><a href="category.html#food">Food</a></li>
                          <li><a href="category.html#wtf">WTF</a></li>
                          <li><a href="category.html#comic">Comic</a></li>
                        </ul>
                    </li>
                </ul>
                
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="login.html">Log in</a>
                    </li>
                    <li>
                        <a href="signup.html">Sign up</a>
                    </li>
                    <li>
                        <a href="upload.html" class="strong">Upload</a>
                    </li>
                </ul>
            </div><!--/.nav-collapse -->
            
        </div>
        
    </div><!--/.navbar -->

    <!-- #Content -->
    <div id="content" class="container clearfix">
        
        <?php echo $this->content; ?>
        
    </div><!-- /.container -->
    
    <?php echo $this->inlineScript() ?>
</body>
</html>
