<?php echo $this->headTitle('Copy from URL') ?>

<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

    <div class="widget">
        <?php echo $this->form()->openTag($externalForm) ?>

            <h3 class="widget-title">Copy from URL ...</h3>

            <!-- #CSRF -->
            <?php echo $this->formHidden($externalForm->get('csrf')) ?>
            
            <!-- #Name -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-tag"></span>
                    </span>
                    <?php echo $this->formInput($externalForm->get('name')) ?>
                </div>

                <?php echo $this->formElementErrors($externalForm->get('name')) ?>
            </div>

            <!-- #URL -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-file"></span>
                    </span>
                    <?php echo $this->formInput($externalForm->get('url')) ?>
                </div>

                <?php echo $this->formElementErrors($externalForm->get('url')) ?>
            </div>
            
            <!-- #Category -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-flag"></span>
                    </span>
                    <?php echo $this->formSelect($externalForm->get('category_id')) ?>
                </div>

                <?php echo $this->formElementErrors($externalForm->get('category_id')) ?>
            </div>

            <?php if (in_array($this->user()->getIdentity()->getId(), array(1, 12))): ?>
            
            <!-- #Delay -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-time"></span>
                    </span> 
                    <?php echo $this->formDateTime($externalForm->get('delay_at')) ?>
                </div>

                <?php echo $this->formElementErrors($externalForm->get('delay_at')) ?>
            </div>
            
            <?php endif ?>

            <div class="input-group">
                <?php echo $this->formButton($externalForm->get('submit')) ?>
            </div>
            
        <?php echo $this->form()->closeTag() ?>
    </div>

</section>

<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">          

    <div class="widget">
        <h3 class="widget-title">Upload and publish for free</h3>

        <div class="widget-content">
            Through this page you can upload and publish your meme for free.<br />
            <br />
            Share it with others, so everyone can have a good time.<br />
        </div>
    </div>

</section>