<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

    <div class="widget">
        <?php echo $this->form()->openTag($externalForm) ?>

            <h3 class="widget-title">Copy from URL ...</h3>

            <!-- #Name -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-tag"></span>
                    </span>
                    <?php echo $this->formInput($externalForm->get('name')) ?>
                </div>

                <?php echo $this->formElementErrors($externalForm->get('name')) ?>
            </div>

            <!-- #URL -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-file"></span>
                    </span>
                    <?php echo $this->formInput($externalForm->get('url')) ?>
                </div>

                <?php echo $this->formElementErrors($externalForm->get('url')) ?>
            </div>
            
            <!-- #Category -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-flag"></span>
                    </span>
                    <?php echo $this->formSelect($externalForm->get('category')) ?>
                </div>

                <?php echo $this->formElementErrors($externalForm->get('category')) ?>
            </div>

            <div class="input-group">
                <?php echo $this->formButton($externalForm->get('submit')) ?>
            </div>
            
        <?php echo $this->form()->closeTag() ?>
    </div>

</section>