<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">

    <div class="widget">
        <?php echo $this->form()->openTag($uploadForm) ?>
            
        <h3 class="login-title">Upload from computer ...</h3>

        <!-- #Name -->
        <div class="form-row">
            <div class="input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-tag"></span>
                </span>
                <?php echo $this->formInput($uploadForm->get('name')) ?>
            </div>

            <?php echo $this->formElementErrors($uploadForm->get('name')) ?>
        </div>
        
        <?php if (!isset($tempFile)): ?>
        
        <!-- #File -->
        <div class="form-row">
            <div class="input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-file"></span>
                </span>
                <?php echo $this->formFile($uploadForm->get('file')) ?>
            </div>

            <?php echo $this->formElementErrors($uploadForm->get('file')) ?>
        </div>
        
        <?php endif ?>

        <!-- #Category -->
        <div class="form-row">
            <div class="input-group">
                <span class="input-group-addon">
                    <span class="glyphicon glyphicon-flag"></span>
                </span> 
                <?php echo $this->formSelect($uploadForm->get('category')) ?>
            </div>

            <?php echo $this->formElementErrors($uploadForm->get('category')) ?>
        </div>

        <div class="input-group">
            <?php echo $this->formButton($uploadForm->get('submit')) ?>
        </div>
            
        <?php echo $this->form()->closeTag() ?>
    </div>
    
    <?php if (isset($tempFile)): ?>
    
        Uploaded file:
        <?php echo $tempFile ?>
    
    <?php endif ?>

</section>
