<?php $this->headTitle()->append('Reset password') ?>

<section class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
    
    <div class="widget">
        <h3 class="widget-title">Reset password</h3>
        
         <?php echo $this->form()->openTag($passwordForm) ?>
            
            <!-- #CSRF -->
            <?php echo $this->formHidden($passwordForm->get('csrf')) ?>
            
            <!-- #Password -->
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-envelope"></span>
                    </span>
                    <?php echo $this->formInput($passwordForm->get('password')) ?>
                </div>

                <?php echo $this->formElementErrors($passwordForm->get('password')) ?>
            </div>
            
            <div class="form-row">
                <div class="input-group">
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-envelope"></span>
                    </span>
                    <?php echo $this->formInput($passwordForm->get('password_verify')) ?>
                </div>

                <?php echo $this->formElementErrors($passwordForm->get('password_verify')) ?>
            </div>
            
            <!-- #Submit -->
            <div class="input-group">
                <?php echo $this->formSubmit($passwordForm->get('submit')) ?>
            </div>
            
        <?php echo $this->form()->closeTag() ?>
    </div>

</section>